// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.18.0

package dbconn

import (
	"time"
)

type Post struct {
	PostID    string
	Title     string
	Content   string
	CreatedAt time.Time
	UpdatedAt time.Time
	Draft     bool
}

type PostTag struct {
	PostID string
	Tag    string
}
