// Code generated by qtc from "basepage.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/basepage.qtpl:1
package templates

//line templates/basepage.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/basepage.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/basepage.qtpl:2
type Page interface {
//line templates/basepage.qtpl:2
	Title() string
//line templates/basepage.qtpl:2
	StreamTitle(qw422016 *qt422016.Writer)
//line templates/basepage.qtpl:2
	WriteTitle(qq422016 qtio422016.Writer)
//line templates/basepage.qtpl:2
	Body() string
//line templates/basepage.qtpl:2
	StreamBody(qw422016 *qt422016.Writer)
//line templates/basepage.qtpl:2
	WriteBody(qq422016 qtio422016.Writer)
//line templates/basepage.qtpl:2
}

//line templates/basepage.qtpl:9
func StreamPageTemplate(qw422016 *qt422016.Writer, p Page) {
//line templates/basepage.qtpl:9
	qw422016.N().S(`
<html>
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <link href="/css/output.css" rel="stylesheet">
      <title>`)
//line templates/basepage.qtpl:15
	p.StreamTitle(qw422016)
//line templates/basepage.qtpl:15
	qw422016.N().S(`</title>
    </head>
    <body>
      <div class="top-0 z-40 w-full backdrop-blur flex-none>
        <div class="max-w-8xl mx-auto">
          <div class="py-4 lg:px-8 mx-4 lg:mx-0">
            <div class="relative flex items-center">
              <a class="mr-3 text-2xl flex-none text-neutral_orange hover:font-bold font-semibold overflow-hidden md:w-auto" href="/">xynos space</a>
            </div>
          </div>
        </div>
      </div>
      `)
//line templates/basepage.qtpl:27
	p.StreamBody(qw422016)
//line templates/basepage.qtpl:27
	qw422016.N().S(`
    </body>
</html>
`)
//line templates/basepage.qtpl:30
}

//line templates/basepage.qtpl:30
func WritePageTemplate(qq422016 qtio422016.Writer, p Page) {
//line templates/basepage.qtpl:30
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/basepage.qtpl:30
	StreamPageTemplate(qw422016, p)
//line templates/basepage.qtpl:30
	qt422016.ReleaseWriter(qw422016)
//line templates/basepage.qtpl:30
}

//line templates/basepage.qtpl:30
func PageTemplate(p Page) string {
//line templates/basepage.qtpl:30
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/basepage.qtpl:30
	WritePageTemplate(qb422016, p)
//line templates/basepage.qtpl:30
	qs422016 := string(qb422016.B)
//line templates/basepage.qtpl:30
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/basepage.qtpl:30
	return qs422016
//line templates/basepage.qtpl:30
}
