// Code generated by qtc from "index.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/index.qtpl:1
package templates

//line templates/index.qtpl:1
import (
	"github.com/thexyno/xynoblog/db"
)

//line templates/index.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/index.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/index.qtpl:7
type IndexPage struct {
	Posts []db.Post
}

//line templates/index.qtpl:13
func (p *IndexPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/index.qtpl:13
	qw422016.N().S(`
	This is the main page
`)
//line templates/index.qtpl:15
}

//line templates/index.qtpl:15
func (p *IndexPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/index.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:15
	p.StreamTitle(qw422016)
//line templates/index.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:15
}

//line templates/index.qtpl:15
func (p *IndexPage) Title() string {
//line templates/index.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:15
	p.WriteTitle(qb422016)
//line templates/index.qtpl:15
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:15
	return qs422016
//line templates/index.qtpl:15
}

//line templates/index.qtpl:18
func (p *IndexPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/index.qtpl:18
	qw422016.N().S(`
	<div class="mx-auto container">
	<h1 class="px-8 py-8 text-2xl font-semibold">Posts:</h1>
    `)
//line templates/index.qtpl:21
	if len(p.Posts) == 0 {
//line templates/index.qtpl:21
		qw422016.N().S(`
		No posts.
	`)
//line templates/index.qtpl:23
	} else {
//line templates/index.qtpl:23
		qw422016.N().S(`
			`)
//line templates/index.qtpl:24
		streamemitPosts(qw422016, p.Posts)
//line templates/index.qtpl:24
		qw422016.N().S(`
	`)
//line templates/index.qtpl:25
	}
//line templates/index.qtpl:25
	qw422016.N().S(`
	</div>
`)
//line templates/index.qtpl:27
}

//line templates/index.qtpl:27
func (p *IndexPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/index.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:27
	p.StreamBody(qw422016)
//line templates/index.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:27
}

//line templates/index.qtpl:27
func (p *IndexPage) Body() string {
//line templates/index.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:27
	p.WriteBody(qb422016)
//line templates/index.qtpl:27
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:27
	return qs422016
//line templates/index.qtpl:27
}

//line templates/index.qtpl:29
func streamemitPosts(qw422016 *qt422016.Writer, posts []db.Post) {
//line templates/index.qtpl:29
	qw422016.N().S(`
   `)
//line templates/index.qtpl:30
	for _, v := range posts {
//line templates/index.qtpl:30
		qw422016.N().S(`
   <div class="">
    <h3 class="font-semibold text-lg">`)
//line templates/index.qtpl:32
		qw422016.E().S(v.Title)
//line templates/index.qtpl:32
		qw422016.N().S(`</h3>
    <div class="text-black">`)
//line templates/index.qtpl:33
		qw422016.E().S(v.Content)
//line templates/index.qtpl:33
		qw422016.N().S(`</div>
    <p class="text-xs font-thin text-slate-500">Released On: `)
//line templates/index.qtpl:34
		qw422016.E().S(v.Created.Format("2006-01-02T15:04:05Z07:00"))
//line templates/index.qtpl:34
		qw422016.N().S(`</p>
    </div>
    `)
//line templates/index.qtpl:36
	}
//line templates/index.qtpl:36
	qw422016.N().S(`
`)
//line templates/index.qtpl:37
}

//line templates/index.qtpl:37
func writeemitPosts(qq422016 qtio422016.Writer, posts []db.Post) {
//line templates/index.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/index.qtpl:37
	streamemitPosts(qw422016, posts)
//line templates/index.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line templates/index.qtpl:37
}

//line templates/index.qtpl:37
func emitPosts(posts []db.Post) string {
//line templates/index.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/index.qtpl:37
	writeemitPosts(qb422016, posts)
//line templates/index.qtpl:37
	qs422016 := string(qb422016.B)
//line templates/index.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/index.qtpl:37
	return qs422016
//line templates/index.qtpl:37
}
