// Code generated by qtc from "posts.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/posts.qtpl:1
package templates

//line templates/posts.qtpl:1
import (
	"github.com/thexyno/xynoblog/db"
)

//line templates/posts.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/posts.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/posts.qtpl:7
type PostsPage struct {
	Posts []db.Post
}

//line templates/posts.qtpl:13
func (p *PostsPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/posts.qtpl:13
	qw422016.N().S(`
	Posts - xynos space
`)
//line templates/posts.qtpl:15
}

//line templates/posts.qtpl:15
func (p *PostsPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/posts.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/posts.qtpl:15
	p.StreamTitle(qw422016)
//line templates/posts.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line templates/posts.qtpl:15
}

//line templates/posts.qtpl:15
func (p *PostsPage) Title() string {
//line templates/posts.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/posts.qtpl:15
	p.WriteTitle(qb422016)
//line templates/posts.qtpl:15
	qs422016 := string(qb422016.B)
//line templates/posts.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/posts.qtpl:15
	return qs422016
//line templates/posts.qtpl:15
}

//line templates/posts.qtpl:18
func (p *PostsPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/posts.qtpl:18
	qw422016.N().S(`
	<div class="mx-auto container max-w-6xl">
	<h3 class="pt-4 text-xl font-semibold">Posts:</h3>
      <div class="px-8 flex flex-col">
      `)
//line templates/posts.qtpl:22
	if len(p.Posts) == 0 {
//line templates/posts.qtpl:22
		qw422016.N().S(`
	  	No posts.
	  `)
//line templates/posts.qtpl:24
	} else {
//line templates/posts.qtpl:24
		qw422016.N().S(`
	  		`)
//line templates/posts.qtpl:25
		streamemitPosts(qw422016, p.Posts)
//line templates/posts.qtpl:25
		qw422016.N().S(`
	  `)
//line templates/posts.qtpl:26
	}
//line templates/posts.qtpl:26
	qw422016.N().S(`
	  </div>
	</div>
`)
//line templates/posts.qtpl:29
}

//line templates/posts.qtpl:29
func (p *PostsPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/posts.qtpl:29
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/posts.qtpl:29
	p.StreamBody(qw422016)
//line templates/posts.qtpl:29
	qt422016.ReleaseWriter(qw422016)
//line templates/posts.qtpl:29
}

//line templates/posts.qtpl:29
func (p *PostsPage) Body() string {
//line templates/posts.qtpl:29
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/posts.qtpl:29
	p.WriteBody(qb422016)
//line templates/posts.qtpl:29
	qs422016 := string(qb422016.B)
//line templates/posts.qtpl:29
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/posts.qtpl:29
	return qs422016
//line templates/posts.qtpl:29
}
