// Code generated by qtc from "post.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line templates/post.qtpl:1
package templates

//line templates/post.qtpl:1
import (
	"github.com/thexyno/xynoblog/db"
)

//line templates/post.qtpl:6
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line templates/post.qtpl:6
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line templates/post.qtpl:7
type PostPage struct {
	Post            db.Post
	RenderedContent []byte
}

//line templates/post.qtpl:13
func (p *PostPage) StreamTitle(qw422016 *qt422016.Writer) {
//line templates/post.qtpl:13
	qw422016.N().S(`
	`)
//line templates/post.qtpl:14
	qw422016.E().S(p.Post.Title)
//line templates/post.qtpl:14
	qw422016.N().S(` - Xynos Space
`)
//line templates/post.qtpl:15
}

//line templates/post.qtpl:15
func (p *PostPage) WriteTitle(qq422016 qtio422016.Writer) {
//line templates/post.qtpl:15
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/post.qtpl:15
	p.StreamTitle(qw422016)
//line templates/post.qtpl:15
	qt422016.ReleaseWriter(qw422016)
//line templates/post.qtpl:15
}

//line templates/post.qtpl:15
func (p *PostPage) Title() string {
//line templates/post.qtpl:15
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/post.qtpl:15
	p.WriteTitle(qb422016)
//line templates/post.qtpl:15
	qs422016 := string(qb422016.B)
//line templates/post.qtpl:15
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/post.qtpl:15
	return qs422016
//line templates/post.qtpl:15
}

//line templates/post.qtpl:18
func (p *PostPage) StreamBody(qw422016 *qt422016.Writer) {
//line templates/post.qtpl:18
	qw422016.N().S(`
	<div class="mx-auto container">
	<h1 class="px-8 py-8">`)
//line templates/post.qtpl:20
	qw422016.E().S(p.Post.Title)
//line templates/post.qtpl:20
	qw422016.N().S(`</h1>
	`)
//line templates/post.qtpl:21
	qw422016.N().Z(p.RenderedContent)
//line templates/post.qtpl:21
	qw422016.N().S(`
	</div>
`)
//line templates/post.qtpl:23
}

//line templates/post.qtpl:23
func (p *PostPage) WriteBody(qq422016 qtio422016.Writer) {
//line templates/post.qtpl:23
	qw422016 := qt422016.AcquireWriter(qq422016)
//line templates/post.qtpl:23
	p.StreamBody(qw422016)
//line templates/post.qtpl:23
	qt422016.ReleaseWriter(qw422016)
//line templates/post.qtpl:23
}

//line templates/post.qtpl:23
func (p *PostPage) Body() string {
//line templates/post.qtpl:23
	qb422016 := qt422016.AcquireByteBuffer()
//line templates/post.qtpl:23
	p.WriteBody(qb422016)
//line templates/post.qtpl:23
	qs422016 := string(qb422016.B)
//line templates/post.qtpl:23
	qt422016.ReleaseByteBuffer(qb422016)
//line templates/post.qtpl:23
	return qs422016
//line templates/post.qtpl:23
}
